title: Gabryella Facchini
description: Artigos sobre tecnologia, carreira e produtividade.
url: "https://gabyfacchini.github.io"
baseurl: ""  # Se o seu reposit√≥rio for o principal (username.github.io), deixe vazio.